### ISSUE TITLE
Editor written in Elm

### ISSUE THREAD

**Issue by jameskolce** [lijunsong/pollen-rock#29]
Hi again @lijunsong, I was planning to write a new editor in Elm for Pollen Rock but I just saw that you already started one in the `dev` branch, although it looks incomplete.

What are your plans? Perhaps I could take care of the editor.

In any case, I have started making changes for myself here https://github.com/jameskolce/pollen-rock/tree/dev-alt

**Comment by lijunsong** [comment]
Hi @jameskolce 

The Elm version of the editor should have long been done. Life is just too busy :(

Let me address your questions on pollen-rock installation. You don't need to clone to repo to do install if you just want to use it. I think the README is relatively clear on how to do a clean installation and use it. Yes, you do `raco pkg install pollen-rock` and you can start using it. You can create files/folders from the app in the stable version. The currently stable version is all written in JS, without any automated test or unittest.

Now speaking of the Elm implementation, I am so happy that you're willing to start it, even though I haven't made this project ready for others to contribute/takeover (docs are incomplete, RESTful APIs are not documented, etc.)

Since you've started, cool, let's do that. Feel free to modify the code or start your own code. Lots of features need to implement, but the hard part is to design the app to encourage writing with focus, and compiling pollen with ease (That was the purpose to start pollen-rock).

I've planned many features in README (auto render, autocomplete, syntax check, etc). Most of these features require a support from the server. So you might end up with working on servers eventually (though I believe my time spent on pollen-rock server has made the server in really good shape).

The current progress of dev branch is that I am working on filesystem indexing (for the landing page). I encourage you to take a look at integration Elm and CodeMirror to see if it's necessary to write the lexing/parsing in Elm (The old version has a Pollen parser that I wrote in quick just to make it work). This is just a suggestion. Do what makes sense to push forward this project.

Let me know if you have any questions, and suggestions.

**Comment by jameskolce** [comment]
Thanks for the detailed reply!

Don't worry about making it ready for contributors, I can just read the code! I just did that with the new editor of the dev branch and made some changes to simplify things, for example, I deleted webpack and reorganized everything related to that, adding a simple package to execute commands in parallel, now `npm start` will run everything necessary to start coding (the "bundling" processes weren't quite necessary either). Now feels more organized to start working on it :)

I think the design is now going to be the easy part and I think I'm good at simplifying things, so no worries. I actually wanted to make a new editor for this project for that reason; just to have something more intuitive to focus on writing my blog.

Working with the server might be a problem just at the beginning because I have absolutely no experience with Racket, but I want to learn and I'm very interested in Lisp languages in general, so eventually, I'll be able to do it. For now, I can work on the editor with the features that the server already provides, although the JSON server that you added looks like a good place to start testing things.

The integration of Elm with JS libraries shouldn't be an issue, although it would be interesting to write a parser and all that using Elm, I would be willing to give it a try.

Feel free to treat me in this project like some kind of apprentice: you can share with me ideas or tasks to do and give me some direction, then I can work on those things. In that way I learn, gain experience and the project can progress at the same time, especially with anything related to Racket, I feel like I can do everything else with no problem.

Do you prefer that I send pull requests to the dev branch or can I push commits directly?

Thanks

**Comment by lijunsong** [comment]
Cool! I am fine with pushing code directly as long as you know what you’re
doing. But for now, I won’t have too much time working on this in next
three weeks, and I am afraid of losing context once you started pushing
code like crazy. Could you still send pull request in next a few weeks?
This can also force you group your commits in a reasonable way to be a
reviewable change set. Once we figure that out and want to move faster, we
can chat in IRC or slack to solve problems in real time.

**Comment by jameskolce** [comment]
That's alright! I understand the part of losing context, I'll be working on my fork without doing too many drastic changes, for now, I just want to mainly get it working as simple as possible. I haven't checked the Elm code in depth yet so I'll let you know what I'll be doing once I get into it.

Chatting in Slack sounds good to me, once you get ready for that just let me know.

**Comment by jameskolce** [comment]
I'll close this one as solved
