### ISSUE TITLE
Elm project setup in dev branch

### ISSUE THREAD

**Issue by lijunsong** [lijunsong/pollen-rock#30]
Pollen-rock in dev branch is getting better:

- We’ve switched from JSON RPC to RESTful API, which can provide a lot more useful project information in a more flexible way.
- We’ve started unit test the server. Every RESTful API now has a unittest.
- We’ve started server integration test

Now it’s time to write the RESTful API spec (will open a different issue) and start working on front end.

In dev branch, our front end will be written in Elm (Yes!), and we want to set up the following things to make this project great again☝🏻

- One command to spin up server and the elm dev server (file change watch is a must)
- One command to compile the app to `/editor/dist/index.html` directory (Elm will be SPA) and this file will be read by the server.
- The pollen-rock server should handle SPA application (handle 404 page, etc.)
- README in /editor/README to describe the front end development flow.

**Comment by lijunsong** [comment]
@jameskolce Feel free to send out your diff so I can also work on the front end using your change :D

**Comment by jameskolce** [comment]
The pull request is up!

**Comment by jameskolce** [comment]
I think my changes cover all those points with the exception of the third one.

- `npm start` will start everything including a watcher for Elm.
- `npm run build` will compile the application and will produce a main.js file in a `public` folder. I didn't use the `dist` name because it sounds like a target for compilation only, but that folder also contains the index.html and the styles.css which are not the product of any compilation process (yet).
- I updated the README file to include the new commands.

**Comment by jameskolce** [comment]
Instead of producing a `main.js` file after compiling Elm, we can also produce the final `index.html` with everything integrated as you mention, although I think we would have to first check the existing solutions in Elm to work with CSS and if they are not flexible enough we would have to set up a CSS preprocessor too, I'm currently working on a new one so I can take care of that.

**Comment by lijunsong** [comment]
@jameskolce Finally I have time now. I have an idea here. Let's separate the server and Elm editor to two projects. Both will publish to racket package site. From racket package's point of view, server will depend on Pollen, and the Elm editor will depend on the server package.

This would benefit both side of the world.  I realized this would be good when I worked on the document. It makes no sense to put the two inside one package and write document on both of them all at once. They're logically two projects, and should have two documents.

Separating the two also makes sense if we have more front ends coming in, say Atom, which really needs just the server. What do you think?

**Comment by jameskolce** [comment]
That makes perfect sense to me. How do you want to organize the projects? Perhaps it could be a good idea to create a Github Org and put all the projects there.

I have a question: Why should the Elm editor be published on the Racket package site? Since it won't contain Racket code it could be distributed as an "independent" project lets say, no? Perhaps just cloning the repository or something. Or distribute it through NPM since that's the package manager that Elm requires anyway.

**Comment by lijunsong** [comment]
My consideration is the people who uses Pollen. If I were them, I would wish the app would have few dependencies, and even better, working out of box. Now they have installed Pollen-rock (the server), and then what? and you want them to install npm, or clone another repo (and clone to where?) that would be just too much. Remember they're not programmers.

The editor can have build dependencies on NPM, but using the app doesn't require NPM or anything related. So AFAIK, Racket package is the only way to go. Correct me if I am wrong here.

**Comment by jameskolce** [comment]
Ah, you are right, I was thinking just about the Elm source files, but it will include the compiled files too.

Sounds good. I haven't done anything as I wanted yet but I hope to get into it these days if I get other projects in good shape.

**Comment by lijunsong** [comment]
Dev branch removed.
